### PR TITLE
Added new Bragg peak functional and auto Brillouin zone determination

### PR DESCRIPTION
**Pull request by trbritt**
- Fixes Issue: :func:`bragg_peaks` fails to identify all peaks in newly found datasets. New function :func:`bragg_peaks_persistence` uses the ideas of 2D persistence (see function documentation) to determine all local maxima. Thresholding the peak prominence allows for looser or stricter tolerances for peak determination, allowing more flexibility than the crossed phase correlation approach.
- Fixes Issue: Now includes the class :class:`brillouin_zones` which allows for the automatic determination of BZ projections in the given 2D geometry based on the Voronoi regions of the Bragg peaks. Class methods allow for determination of entirely visible reflections, visualization of these BZ boundaries, as well as determination of equivalent reduced scattering vectors for single crystal datasets. 
- [x] `CHANGELOG.rst` updated.
- Changes Proposed by this Pull Request:
  - Added- :func:`bragg_peaks_persistence`
  - Added- Test scripts `test_indexing_persistence` and `test_brillouin` to ensure validity
  - Added- Documentation and tutorials (with all sphinx docs testing passed)

### CODE REVIEW

**Comment by LaurentRDC** [comment]
You'll need to run `black` over the code base for the linting workflow to pass

**Comment by LaurentRDC** [comment]
Your version of black must be outdated

**Comment by LaurentRDC** [comment]
I used black 22.1.0

**Comment by trbritt** [comment]
I used the same version as well. For some reason when I last ran it over the code base it added spaces next to exponentiation symbols, but then when I ran it again, it removed those same spaces, so not too sure what happened. I'll look into it.

**Comment by LaurentRDC** [comment]
Release 2.1.11 is underway! might take up to 24h to get conda-forge to notice, but sometimes it's only a few hours

**Comment by trbritt** [comment]
Last workflow (Continuous integration #157) failed at release stage, some issue uploading to PyPi.

**Comment by LaurentRDC** [comment]
conda-forge has [picked up the changes](https://github.com/conda-forge/scikit-ued-feedstock/pull/32). It might be installable now

**Pull request merged**
